name: 'Telegram Action'
description: 'Telegram notification for workflow set up with GitHub Actions'
author: 'xinthink'
branding:
  icon: 'send'
  color: 'blue'
inputs:
  botToken:
    description: 'The Telegram Bot token'
    required: true
  chatId:
    description: 'The target to which the message will be sent, can be a Telegram Channel or Group'
    required: true
  jobStatus:
    description: "The current status of the job: job.status, defaults to 'success'"
    default: 'success'
  skipSuccess:
    description: "Only non-success notifications will be sent if true, include success notifications otherwise, defaults to 'true'"
    default: 'true'
runs:
  using: 'node12'
  main: 'lib/main.js'
